name: CI build

on: [push]

jobs:
  create_type_docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: master

      - uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Retrieve the cached "node_modules" directory (if present)
        uses: actions/cache@v3
        id: node-cache
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies (if the cached directory was not found)
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Create the docs directory locally in CI
        id: create-docs
        run: >
          npm run docs &&
          echo "STATE=true" >> "$GITHUB_OUTPUT"

      - name: Test copying Public to docs
        id: copy-images
        if: steps.create-docs.outputs.STATE == 'true'
        run: >
          cp -r public docs &&
          cp .gitignore docs &&
          echo ${{ steps.create-docs.outputs }} >> docs/output.txt &
          echo "COPIED=true" >> "$GITHUB_OUTPUT"

      - name: Deploy Docs 🚀
        if: steps.copy-images.outputs.COPIED == 'true'
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs
