name: CI build

on:
  workflow_run:
    workflows: ["generateReadmeTree"]
    types:
      - completed

jobs:
  create_type_docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: master

      - name: PNPM Setup
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.3.1
          run_install: false

      - name: Node Setup
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Create the docs directory locally in CI
        id: create-docs
        run: >
          cd apps/experimentalapp &&
          pnpm run prebuild &&
          pnpm run docs &&
          echo "STATE=true" >> "$GITHUB_OUTPUT"

      - name: Test copying Public to docs
        id: copy-images
        if: steps.create-docs.outputs.STATE == 'true'
        run: >
          cd apps/experimentalapp &&
          cp -r public docs &&
          cp .gitignore docs &&
          cp ignore-step.sh docs &&
          echo ${{ steps.create-docs.outputs }} >> docs/output.txt &
          echo "COPIED=true" >> "$GITHUB_OUTPUT"

      - name: Deploy Docs 🚀
        if: steps.copy-images.outputs.COPIED == 'true'
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: apps/experimentalapp/docs
