name: generateReadmeTree

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      # This is how you use the ga-dree action
      - name: Inject dree
        uses: "euberdeveloper/ga-dree@main"
        with:
          showMadeWithDree: "false" # Does not add "Made with dree"
          # comment: "my-custom-dree-comment" # [//]: # (comment) Default dree
          targetPath: "./apps/experimentalapp/README.md" # The path of the file where the tree should be injected
          config: "./apps/experimentalapp/dree.config.json"

      # In this step the changes to the branch are committed
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs: inject dree (automated commit)"
          branch: master